import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { BrowserBridge } from '../bridge.mjs';
const origin = 'chrome-extension://' + 'a'.repeat(32);
const settings = { geminiEnabled: true, chatgptEnabled: true, grokEnabled: true, aistudioEnabled: true, chatgptReasoningEndEnabled: true, tabKeepAliveEnabled: false, notificationEnabled: true, soundEnabled: true, soundVolume: 1 };
test('配对码一次性且限时、绑定扩展来源、持久化与撤销', t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'relay-pair-test-')); t.after(() => fs.rmSync(dir, { recursive: true }));
  const bridge = new BrowserBridge(dir);
  assert.throws(() => bridge.connect('bad', origin));
  const { code } = bridge.issue(); bridge.expires = 0; assert.throws(() => bridge.connect(code, origin));
  const fresh = bridge.issue(); const { token } = bridge.connect(fresh.code, origin);
  assert.throws(() => bridge.connect(fresh.code, origin));
  assert.throws(() => bridge.sync(token, 'chrome-extension://' + 'b'.repeat(32), { settings }));
  assert.throws(() => bridge.sync('bad', origin, { settings }));
  assert.throws(() => bridge.sync(token, origin, { settings: { ...settings, command: 'bad' } }));
  const restarted = new BrowserBridge(dir);
  restarted.sync(token, origin, { settings, version: '1.3.0' });
  assert.equal(restarted.status().settings.soundVolume, 1);
  restarted.revoke(); assert.throws(() => restarted.sync(token, origin, { settings }));
  assert.equal(fs.statSync(path.join(dir, 'browser-pair.json')).mode & 0o777, 0o600);
});
test('设置必须收到匹配确认，不能把排队当成功；撤销拒绝未完成写入', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'relay-sync-test-')); t.after(() => fs.rmSync(dir, { recursive: true }));
  const bridge = new BrowserBridge(dir); const { token } = bridge.connect(bridge.issue().code, origin);
  bridge.sync(token, origin, { settings });
  const saved = bridge.save({ grokEnabled: false });
  assert.throws(() => bridge.save({ soundEnabled: false }));
  const { pending } = bridge.sync(token, origin, { settings });
  assert.ok(bridge.sync(token, origin, { settings, ack: pending.id }).pending);
  bridge.sync(token, origin, { settings: { ...settings, grokEnabled: false }, ack: pending.id });
  assert.equal((await saved).settings.grokEnabled, false);
  const cancelled = bridge.save({ soundEnabled: false }); bridge.revoke(); await assert.rejects(cancelled);
});

test('公共设置首次不覆盖，修改按字段同步，重启后保留基线且等待桌面写入确认', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'relay-shared-test-'));
  t.after(() => fs.rmSync(dir, { recursive: true }));
  const changes = [];
  const options = { onSharedChange: patch => changes.push(patch) };
  let bridge = new BrowserBridge(dir, options);
  const { token } = bridge.connect(bridge.issue().code, origin);
  bridge.sync(token, origin, { settings });
  assert.deepEqual(changes, []);
  const updated = { ...settings, soundVolume: 1.25, soundEnabled: false };
  bridge.sync(token, origin, { settings: updated });
  assert.deepEqual(changes, [{ soundEnabled: false, soundVolume: 1.25 }]);
  bridge = new BrowserBridge(dir, options);
  bridge.sync(token, origin, { settings: updated });
  assert.equal(changes.length, 1);
  const saved = bridge.save({ soundVolume: 0.5 });
  const { pending } = bridge.sync(token, origin, { settings });
  assert.equal(changes.length, 1);
  bridge.sync(token, origin, { settings: { ...updated, soundVolume: 0.5 }, ack: pending.id });
  await saved;
  assert.deepEqual(changes[1], { soundVolume: 0.5 });
});
